# Docker-compose.yml file for Pyblabber
# Jonathan Lacson
# CS 2304 Spring 2019

version: "3.7"

# define our images:
services:
  # should be plug and play, no intervention required
  pyblabber-client:
    image: vtcs2304s19/blabber-client
    networks:
      default:
        aliases:
          - client
          - pyblabber-client
    labels:
      traefik.backend: "client"
      traefik.port: "80"
      traefik.frontend.rule: "PathPrefix:/"
  # our handmade container
  pyblabber-api:
    image: pyblabber:latest
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
    read_only: true
    healthcheck:
      test: curl http://localhost:5000/status
      interval: 90s
      timeout: 10s
      retries: 2
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - 5000:5000
    networks:
      default:
        aliases:
          - api
          - pyblabber-api
    labels:
      traefik.backend: "api"
      traefik.port: 5000
      traefik.frontend.rule: "PathPrefix:/api"
      traefik.frontend.rule: "PathPrefixStrip:/api"
  # a generic mongo image
  pyblabber-datastore:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
    volumes:
      - ./data:/data/db
    networks:
      default:
        aliases:
          - mongo
          - db
    ports:
      - "27017:27017"
  # taken from the traefik webdocs
  traefik-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# define networks
networks:
  default:

# define secrets
secrets:
  MONGO_ROOT_USERNAME:
    file: mongo_username.txt
  MONGO_ROOT_PASSWORD:
    file: mongo_password.txt